### PR TITLE
Pull request for #26: Change `np.NaN` to `np.nan` in main.py

### LINKED ISSUE #26: Change `np.NaN` to `np.nan` in main.py
**Goal:** `np.NaN` has now been removed and must be replaced by `np.nan`. 
**Deliverable:** `main.py` with this line corrected 
https://github.com/JMSLab/BootstrapReport/blob/fcb41dae36dd5d15a5c3c7e4b86bbee22ad9185f/src/BootstrapReport/main.py#L25

### PR DESCRIPTION
**Pull request by liaochris**
@jmshapir This resolves https://github.com/JMSLab/BootstrapReport/issues/26

### CODE REVIEW

**Comment by jmshapir** [comment]
@liaochris thanks!

Two things:
1. I'm seeing some unit tests failing. Can you look into why?
2. Will we also need to update the [shiny app](https://jmslab.shinyapps.io/bootstrapreport/)? If so I should be able to give you privileges to do that.

**Comment by liaochris** [comment]
@jmshapir 
(i) The builds failed because of the problem about x64/arm architectures from https://github.com/JMSLab/Template/pull/99. I fixed it by removing the architecture attribute from the pytest file, the same fix from https://github.com/JMSLab/Template/pull/99. 

(iI) Using [ratio_replicates.csv](https://github.com/JMSLab/BootstrapReport/blob/main/shiny/ratio_replicates.csv), the shiny app seems to work right now. It might be because the shiny app environment is using an older version of numpy where `np.NaN` still works.

**Review by jmshapir — APPROVED** [review]
@liaochris thanks!

If the shiny app is working then let's leave it as is and not redeploy.

After you wrap up can you make a [release](https://github.com/JMSLab/BootstrapReport/releases)?

We're following [semver](https://semver.org/) so I think this will be v3.0.2.

**Comment by liaochris** [comment]
see summary at https://github.com/JMSLab/BootstrapReport/issues/26#issuecomment-2223968012

**Comment by jmshapir** [comment]
@liaochris a few things:
1. I've renamed the pull following our usual convention.
2. Regarding the below, usually we try to avoid making comments after the summary comment in the issue (so that we can rely on the summary comment being the last one). So, I've ported the question over to the pull.
3. The link you used looks right! I encapsulated it and also added a note on the commit at which changes were brought to main.
4. You can delete the branch now thanks!

> @jmshapir Is the link I provided to the latest version of the branch the correct one? It's the one I get when I navigate to the branch -> select the latest commit from the commit history -> click on Browse More Files

**Comment by liaochris** [comment]
Thanks for the corrections! That makes sense.

**Pull request merged**
